/**
 * Wattpad reports a language name ("English"); EPUB metadata needs a BCP-47
 * code. Unlisted languages return null so the caller can say so and fall back.
 */
const CODES_BY_NAME: Record<string, string> = {
  afrikaans: "af",
  arabic: "ar",
  bengali: "bn",
  bulgarian: "bg",
  burmese: "my",
  catalan: "ca",
  chinese: "zh",
  croatian: "hr",
  czech: "cs",
  danish: "da",
  dutch: "nl",
  english: "en",
  estonian: "et",
  filipino: "fil",
  finnish: "fi",
  french: "fr",
  german: "de",
  greek: "el",
  gujarati: "gu",
  hebrew: "he",
  hindi: "hi",
  hungarian: "hu",
  icelandic: "is",
  indonesian: "id",
  italian: "it",
  japanese: "ja",
  kannada: "kn",
  khmer: "km",
  korean: "ko",
  latvian: "lv",
  lithuanian: "lt",
  malay: "ms",
  malayalam: "ml",
  marathi: "mr",
  nepali: "ne",
  norwegian: "no",
  persian: "fa",
  polish: "pl",
  portuguese: "pt",
  punjabi: "pa",
  romanian: "ro",
  russian: "ru",
  serbian: "sr",
  slovak: "sk",
  slovenian: "sl",
  spanish: "es",
  swahili: "sw",
  swedish: "sv",
  tagalog: "fil",
  tamil: "ta",
  telugu: "te",
  thai: "th",
  turkish: "tr",
  ukrainian: "uk",
  urdu: "ur",
  vietnamese: "vi",
};

export function languageCode(name: string | undefined): string | null {
  if (!name) return null;
  return CODES_BY_NAME[name.trim().toLowerCase()] ?? null;
}
